name: Deploy coverage report and documentation to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Docs
        run: "pnpm run docs"

      - name: Build
        run: pnpm run build

      - name: Generate Coverage
        run: "pnpm run test"

      - name: Commit to GitHub Pages
        if: always()
        env:
          GH_TOKEN: ${{ secrets.COVERAGE_TOKEN }}
        run: |
          shopt -s extglob
          git checkout --orphan gh-pages
          rm -rfv !("coverage|documentation") > /dev/null
          echo "djs-testing.nhcarrigan.com" > CNAME
          echo "# Discord JS Testing" > README.md
          echo "[Read the documentation](./documentation)" >> README.md
          echo "[View the coverage report](./coverage)" >> README.md
          git config --global user.name "Naomi Carrigan"
          git config --global user.email "nhcarrigan@gmail.com"
          git add .
          git commit -m "feat: update docs"
          git push -f origin gh-pages
